### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by hexiangquan** [kootenpv/deep_eye2mouse#1]
hi ,can i get your eye dataset?

**Comment by kootenpv** [comment]
Hi, it would be best to train for yourself; currently it does generalise so well, so it will definitely not generalise to yourself.

I'm also currently experimenting with image capture settings. Maybe at a later time I'll be able to share some useful data.

Good luck!

**Comment by hexiangquan** [comment]
thank you for your replay.i also want to do this example. i will do it by myself .thank you 







在2017年04月12 20时35分, "Pascal van Kooten"<notifications@github.com>写道:



Hi, it would be best to train for yourself; currently it does generalise so well, so it will definitely not generalise to yourself.

I'm also currently experimenting with image capture settings. Maybe at a later time I'll be able to share some useful data.

Good luck!
